
package fr.carsat.service.soap.document;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CalculatriceService", targetNamespace = "http://document.soap.service.carsat.fr/", wsdlLocation = "http://localhost:9999/CalculatriceServiceDocument?wsdl")
public class CalculatriceService
    extends Service
{

    private final static URL CALCULATRICESERVICE_WSDL_LOCATION;
    private final static WebServiceException CALCULATRICESERVICE_EXCEPTION;
    private final static QName CALCULATRICESERVICE_QNAME = new QName("http://document.soap.service.carsat.fr/", "CalculatriceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9999/CalculatriceServiceDocument?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CALCULATRICESERVICE_WSDL_LOCATION = url;
        CALCULATRICESERVICE_EXCEPTION = e;
    }

    public CalculatriceService() {
        super(__getWsdlLocation(), CALCULATRICESERVICE_QNAME);
    }

    public CalculatriceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CALCULATRICESERVICE_QNAME, features);
    }

    public CalculatriceService(URL wsdlLocation) {
        super(wsdlLocation, CALCULATRICESERVICE_QNAME);
    }

    public CalculatriceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CALCULATRICESERVICE_QNAME, features);
    }

    public CalculatriceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculatriceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CalculatriceContrat
     */
    @WebEndpoint(name = "CalculatriceServicePort")
    public CalculatriceContrat getCalculatriceServicePort() {
        return super.getPort(new QName("http://document.soap.service.carsat.fr/", "CalculatriceServicePort"), CalculatriceContrat.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalculatriceContrat
     */
    @WebEndpoint(name = "CalculatriceServicePort")
    public CalculatriceContrat getCalculatriceServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://document.soap.service.carsat.fr/", "CalculatriceServicePort"), CalculatriceContrat.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CALCULATRICESERVICE_EXCEPTION!= null) {
            throw CALCULATRICESERVICE_EXCEPTION;
        }
        return CALCULATRICESERVICE_WSDL_LOCATION;
    }

}
