
package fr.orsys.service.calcul;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CalculatriceContrat", targetNamespace = "calcul.service.orsys.fr")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalculatriceContrat {


    /**
     * 
     * @param notifierPart
     */
    @WebMethod(operationName = "Notifier", action = "urn:notifier")
    @Oneway
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public void notifier(
        @WebParam(name = "NotifierRequete", targetNamespace = "calcul.service.orsys.fr", partName = "NotifierPart")
        NotifierRequete notifierPart);

    /**
     * 
     * @param operateur
     * @param operande1
     * @param operande2
     * @return
     *     returns double
     */
    @WebMethod(operationName = "Calculer", action = "urn:calculer")
    @WebResult(name = "Resultat", targetNamespace = "")
    @RequestWrapper(localName = "Calculer", targetNamespace = "calcul.service.orsys.fr", className = "fr.orsys.service.calcul.Calculer")
    @ResponseWrapper(localName = "CalculerResponse", targetNamespace = "calcul.service.orsys.fr", className = "fr.orsys.service.calcul.CalculerResponse")
    public double calculer(
        @WebParam(name = "Operateur", targetNamespace = "")
        Integer operateur,
        @WebParam(name = "Operande1", targetNamespace = "")
        double operande1,
        @WebParam(name = "Operande2", targetNamespace = "")
        double operande2);

}
