
package fr.orsys.service.convert;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ConvertisseurContrat", targetNamespace = "convert.service.orsys.fr")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ConvertisseurContrat {


    /**
     * 
     * @param montantPart
     * @param monnaiePart
     * @return
     *     returns double
     */
    @WebMethod(operationName = "ConvertirMonnaie", action = "urn:Convertir")
    @WebResult(name = "SommePart", partName = "SommePart")
    @Action(input = "urn:Convertir", output = "convert.service.orsys.fr/ConvertisseurContrat/ConvertirMonnaieResponse")
    public double convertirMonnaie(
        @WebParam(name = "MonnaiePart", partName = "MonnaiePart")
        Monnaie monnaiePart,
        @WebParam(name = "MontantPart", partName = "MontantPart")
        double montantPart);

}
