
package fr.orsys.service.convert;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ConvertisseurService", targetNamespace = "convert.service.orsys.fr", wsdlLocation = "http://10.1.1.83:7777/ConvertService?wsdl")
public class ConvertisseurService
    extends Service
{

    private final static URL CONVERTISSEURSERVICE_WSDL_LOCATION;
    private final static WebServiceException CONVERTISSEURSERVICE_EXCEPTION;
    private final static QName CONVERTISSEURSERVICE_QNAME = new QName("convert.service.orsys.fr", "ConvertisseurService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.1.1.83:7777/ConvertService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONVERTISSEURSERVICE_WSDL_LOCATION = url;
        CONVERTISSEURSERVICE_EXCEPTION = e;
    }

    public ConvertisseurService() {
        super(__getWsdlLocation(), CONVERTISSEURSERVICE_QNAME);
    }

    public ConvertisseurService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONVERTISSEURSERVICE_QNAME, features);
    }

    public ConvertisseurService(URL wsdlLocation) {
        super(wsdlLocation, CONVERTISSEURSERVICE_QNAME);
    }

    public ConvertisseurService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONVERTISSEURSERVICE_QNAME, features);
    }

    public ConvertisseurService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConvertisseurService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConvertisseurContrat
     */
    @WebEndpoint(name = "ConvertServicePort")
    public ConvertisseurContrat getConvertServicePort() {
        return super.getPort(new QName("convert.service.orsys.fr", "ConvertServicePort"), ConvertisseurContrat.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConvertisseurContrat
     */
    @WebEndpoint(name = "ConvertServicePort")
    public ConvertisseurContrat getConvertServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("convert.service.orsys.fr", "ConvertServicePort"), ConvertisseurContrat.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONVERTISSEURSERVICE_EXCEPTION!= null) {
            throw CONVERTISSEURSERVICE_EXCEPTION;
        }
        return CONVERTISSEURSERVICE_WSDL_LOCATION;
    }

}
